spring:
  application:
    name: openfeign-customer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: a1a9e1ab-ae9c-4039-844c-c5a6837a3f4b
#监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#使用feign调用是开启hystrix熔断
feign:
  hystrix:
    enabled: true