
version: '2'
services:
  zookeeper:
    image: "wurstmeister/zookeeper"
    hostname: "zookeeper.local"
    container_name: "zookeeper"
    restart: always
    ports:
       - "2181:2181"
    #设置网络别名
    networks:
      local:
        aliases:
          - "zookeeper.local"
  kafka:
    image: "wurstmeister/kafka"
    hostname: "kafka.local"
    container_name: "kafka"
    restart: always
    ports:
      - "9092:9092"
    networks:
      local:
        aliases:
          - "kafka.local"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.105
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./kafka-logs:/kafka
      - /var/run/docker.sock:/var/run/docker.sock

#  kafka-manager:
#    image: sheepkiller/kafka-manager
#    ports:
#      - 9020:9000
#    environment:
#      ZK_HOSTS: zookeeper:2181
      
  redis:
    image: redis
    hostname: "redis.local"
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    #设置网络别名
    networks:
      local:
        aliases:
          - "redis.local"

  #  mysql:
  #    image: mysql
  #    hostname: "mysql.local"
  #    container_name: "mysql"
  #    restart: always
  #    ports:
  #      - "3306:3306"
  #   #设置网络别名
  #    networks:
  #      local:
  #        aliases:
  #          - "mysql.local"
  #    environment:
  #      #密码
  #      MYSQL_ROOT_PASSWORD: "123456"

  nacos:
    image: nacos/nacos-server
    restart: always
    container_name: nacos
    ports:
      - 8848:8848
    environment:
      MODE: standalone


  el
      
#设置网络，名为local
networks:
  local:
    driver: bridge
