#应用名称
spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        enabled: true
        url: http://127.0.0.1:9999
        instance:
          service-base-url: http://127.0.0.1:${server.port}
  #eureka服务端开启登录认证
  security:
    user:
      roles: SUPERUSER
      name: admin
      password: admin
#端口号
server:
  port: 18761

#注册中心相关配置
eureka:
  instance:
    #显示实际IP
    prefer-ip-address: true
  client:
    #不注册服务之eureka
    register-with-eureka: false
    #不发现注册信息
    fetch-registry: false
    #服务地址
    service-url:
      defaultZone: http://admin:admin@localhost:18761/eureka/
  server:
    #每隔60秒检测一下，是否需要踢除失联的客户端
    eviction-interval-timer-in-ms: 60000
    #服务端的自我保护，开启自我保护时，如果客户端丢失的比例大于0.15，就不会踢除客户端
    enable-self-preservation: true
    #ResponceCachImpl 开启只读缓存后，每隔30秒就更新一次只读缓存
    response-cache-update-interval-ms: 30000

#健康信息监控
management:
  endpoint:
    beans:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
