#应用名称
spring:
  application:
    name: zuul-server

#服务端口
server:
  port: 19093

#注册中心
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:18761/eureka/

#健康信息监控
management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude: all

#zuul实现服务路由
zuul:
  prefix: /api
  strip-prefix: true
  routes:
    provider:
      path: /provider/**
      serviceId: eureka-provider
    customer:
      path: /customer/**
      serviceId: eureka-customer
