#应用名称
spring:
  application:
    name: zuul-server
  boot:
    admin:
      client:
        enabled: true
        url: http://127.0.0.1:9999
        instance:
          service-base-url: http://127.0.0.1:${server.port}

#服务端口
server:
  port: 19093

#注册中心
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:18761/eureka/

#健康信息监控
management:
  endpoint:
    beans:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#zuul实现服务路由
zuul:
  prefix: /api
  strip-prefix: true
  routes:
    #面向服务路由
    provider:
      path: /provider/**
      serviceId: eureka-provider
    customer:
      path: /customer/**
      serviceId: eureka-customer
